name: CI
on:
  - push
  - pull_request
jobs:
  core-junit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew core:test --info
      - run: git clone https://sof3:${{secrets.GH_TOKEN}}@github.com/SOF3/enclavlow gh-pages -b gh-pages
      - run: "rm -rf gh-pages/tests/core/${{github.branch}} || true"
      - run: cp -r core/build/reports/tests/test gh-pages/tests/core/${{github.branch}}
      - run: 'git -c "user.email=41898282+github-actions[bot]@users.noreply.github.com" commit -m "Update tests for "${{github.sha}}'
        working-directory: gh-pages
      - run: git push
        working-directory: gh-pages
